name: dart_cloud_run_template
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  shelf: ^1.3.2
  shelf_router: ^1.1.2
  shelf_web_socket: ^1.0.1
  web_socket_channel: ^2.2.0

dev_dependencies:
  rexios_lints: ^3.0.0
  test: ^1.15.7
  test_process: ^2.0.0
  http: ^0.13.0
